### GET ALL USERS
GET http://localhost:3000/api/users

### GET ALL ROLES
GET http://localhost:3000/api/roles

### GET ALL PARTNER
GET http://localhost:3000/api/partner/

### GET ALL PARTNER TYPE
GET http://localhost:3000/api/partnertype/

### GET UNIQUE PARTNERTYPE
GET http://localhost:3000/api/partnertype/1

### GET ALL AEROPUERTOS
GET http://localhost:3000/api/airports

### GET COUNTRY BY CODE
GET http://localhost:3000/api/countries/CL

### GET ALL CONTACT
GET http://localhost:3000/api/contacts?partnerId=2

### GET ALL CONTACTS TYPE
GET http://localhost:3000/api/contactstype

### GET ALL CURRENCIES
GET http://localhost:3000/api/currencies/1

### GET ALL CREDITINFO
GET http://localhost:3000/api/creditinfopartner/1

